### ISSUE TITLE
ATInternet crashes on screen rotate

### ISSUE THREAD

**Issue by misumac** [at-internet/atinternet-apple-sdk#28] opened 2018-03-06 16:04 UTC
Looking at crash reports, it seems that a large number of users are experiencing crashes because of our usage of ATInternet-apple-sdk (version 2.8.6) when they rotate their devices.
The crashes are caused by the force unwrapping of optionals in ScreenOperation.swift, line 51:
ATInternet.sharedInstance.defaultTracker.socketSender!.sendMessage(rotationEvent.description)
Since there are places in the library where optional chaining is used for socketSender and others where it is forced unwrapped just to call methods which do not return anything, could you please use optional chaining everywhere socketSender is concerned?
It seems that there are cases out there in the wild where it will be nil.
Thanks!

**Comment by d-theo** [comment] 2018-03-06 16:16
> Since there are places in the library where optional chaining is used for socketSender and others where it is forced unwrapped just to call methods which do not return anything, could you please use optional chaining everywhere socketSender is concerned?

We will fix the library asap with optional chaining (for socketSender but also everywhere we can)

**Comment by d-theo** [comment] 2018-03-07 10:30
I was able to reproduce some weird issue by turning the screen
Appends that we try to guess the name of a screen by calling `self.navigationController?.navigationBar.topItem?.title` in the SmartTracker.
It looks like that Apple
* Added a new [Main Thread Checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker) that checks if a call to UIKit method/property is allowed or not 
* Reaching UINavigationController.navigationBar.topItem is (now ?) not recommended outside main thread for some reason

**Comment by d-theo** [comment] 2018-03-08 10:20
I pushed a fix for the rotation yesterday, let me know if that solve your issue

**Comment by misumac** [comment] 2018-03-12 12:54
Thank you very much for the swift response and fixes and finding the real cause of the fix!
I noticed the cocoapod is also updated to version 2.8.8 so I included that version in the next build for our beta testers. I will keep an eye for crash reports, but looking at the changes we can safely assume this is fixed.
Please mark this issue as solved if you agree.
Thank you!

**Closed** 2018-03-12 15:09 UTC
